version: '3.8'

services:
  springboot-app:
    image: mezzat9/spring-project:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    depends_on:
      - mysql-db
      - activemq

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61619:61616"
      - "8169:8166"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

volumes:
  mysql_data:
    driver: local
