name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306  # Changed host port to 3307

      activemq:
        image: rmohr/activemq:latest
        ports:
          - 61616:61616  # Changed host port to 61618
          - 8161:8161    # Changed host port to 8163
        env:
          ACTIVEMQ_ADMIN_LOGIN: admin
          ACTIVEMQ_ADMIN_PASSWORD: admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for services to be healthy
        run: |
          sudo docker-compose up -d
          docker-compose ps
          sleep 30

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with detailed logging
        run: ./gradlew test --info --stacktrace --scan
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: password
          SPRING_ACTIVEMQ_BROKER_URL: tcp://localhost:61616
