name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: List files and permissions
      run: ls -l

    - name: Display environment information
      run: printenv

    - name: Start MySQL service
      run: |
        sudo systemctl start mysql
        sudo systemctl status mysql

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with detailed logging
      run: ./gradlew test --info --stacktrace
